title: ""
email: andrea.franceschi@imtlucca.it
description: "personal website"
github_username: AFx3
linkedin_username: afx3
scholar_useranme: 8YDG3tsAAAAJ&hl
orcid_username: 0009-0002-6691-6145
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com


plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - papers.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
